export const items = {
    AMMO: [
        { id: 'ammo.shotgun', name: '12 Gauge Buckshot', image: 'images/ammo/ammo.shotgun' },
        { id: 'ammo.shotgun.fire', name: '12 Gauge Incendiary Shell', image: 'images/ammo/ammo.shotgun.fire' },
        { id: 'ammo.shotgun.slug', name: '12 Gauge Slug', image: 'images/ammo/ammo.shotgun.slug' },
        { id: 'ammo.grenadelauncher.he', name: '40mm HE Grenade', image: 'images/ammo/ammo.grenadelauncher.he' },
        { id: 'ammo.grenadelauncher.buckshot', name: '40mm Shotgun Round', image: 'images/ammo/ammo.grenadelauncher.buckshot' },
        { id: 'ammo.grenadelauncher.smoke', name: '40mm Smoke Grenade', image: 'images/ammo/ammo.grenadelauncher.smoke' },
        { id: 'ammo.rifle', name: '5.56 Rifle Ammo', image: 'images/ammo/ammo.rifle' },
        { id: 'ammo.rifle.explosive', name: 'Explosive 5.56 Rifle Ammo', image: 'images/ammo/ammo.rifle.explosive' },
        { id: 'ammo.handmade.shell', name: 'Handmade Shell', image: 'images/ammo/ammo.handmade.shell' },
        { id: 'ammo.rocket.hv', name: 'High Velocity Rocket', image: 'images/ammo/ammo.rocket.hv' },
        { id: 'ammo.rifle.hv', name: 'HV 5.56 Rifle Ammo', image: 'images/ammo/ammo.rifle.hv' },
        { id: 'ammo.pistol.hv', name: 'HV Pistol Ammo', image: 'images/ammo/ammo.pistol.hv' },
        { id: 'ammo.rifle.incendiary', name: 'Incendiary 5.56 Rifle Ammo', image: 'images/ammo/ammo.rifle.incendiary' },
        { id: 'ammo.pistol.fire', name: 'Incendiary Pistol Bullet', image: 'images/ammo/ammo.pistol.fire' },
        { id: 'ammo.rocket.fire', name: 'Incendiary Rocket', image: 'images/ammo/ammo.rocket.fire' },
        { id: 'ammo.nailgun.nails', name: 'Nailgun Nails', image: 'images/ammo/ammo.nailgun.nails' },
        { id: 'ammo.pistol', name: 'Pistol Bullet', image: 'images/ammo/ammo.pistol' },
        { id: 'ammo.rocket.basic', name: 'Rocket', image: 'images/ammo/ammo.rocket.basic' },
        { id: 'arrow.bone', name: 'Bone Arrow', image: 'images/ammo/arrow.bone' },
        { id: 'arrow.fire', name: 'Fire Arrow', image: 'images/ammo/arrow.fire' },
        { id: 'arrow.hv', name: 'HV Arrow', image: 'images/ammo/arrow.hv' },
        { id: 'speargun.spear', name: 'Speargun Spear', image: 'images/ammo/speargun.spear' },
        { id: 'arrow.wooden', name: 'Arrow', image: 'images/ammo/arrow.wooden' },
        { id: 'explosive.timed', name: 'Explosive Timed C4', image: 'images/ammo/explosive.timed' },
        { id: 'submarine.torpedo.straight', name: 'Torpedo', image: 'images/ammo/submarine.torpedo.straight' }
    ],
    WEAPONS: [
        { id: 'weapon.mod.burstmodule', name: 'Burst Module', image: 'images/weapons/weapon.mod.burstmodule' },
        { id: 'weapon.mod.extendedmags', name: 'Extended Magazine', image: 'images/weapons/weapon.mod.extendedmags' },
        { id: 'weapon.mod.small.scope', name: 'Scope x4', image: 'images/weapons/weapon.mod.small.scope' },
        { id: 'weapon.mod.holosight', name: 'Holosight', image: 'images/weapons/weapon.mod.holosight' },
        { id: 'weapon.mod.muzzleboost', name: 'Muzzle Boost', image: 'images/weapons/weapon.mod.muzzleboost' },
        { id: 'weapon.mod.muzzlebrake', name: 'Muzzle Brake', image: 'images/weapons/weapon.mod.muzzlebrake' },
        { id: 'weapon.mod.simplesight', name: 'Simple Handmade Sight', image: 'images/weapons/weapon.mod.simplesight' },
        { id: 'weapon.mod.silencer', name: 'Silencer', image: 'images/weapons/weapon.mod.silencer' },
        { id: 'weapon.mod.flashlight', name: 'Weapon Flashlight', image: 'images/weapons/weapon.mod.flashlight' },
        { id: 'weapon.mod.lasersight', name: 'Weapon Lasersight', image: 'images/weapons/weapon.mod.lasersight' },
        { id: 'rifle.ak', name: 'Assault Rifle', image: 'images/weapons/rifle.ak' },
        { id: 'grenade.beancan', name: 'Beancan Grenade', image: 'images/weapons/grenade.beancan' },
        { id: 'rifle.bolt', name: 'Bolt Action Rifle', image: 'images/weapons/rifle.bolt' },
        { id: 'bone.club', name: 'Bone Club', image: 'images/weapons/bone.club' },
        { id: 'knife.bone', name: 'Bone Knife', image: 'images/weapons/knife.bone' },
        { id: 'knife.combat', name: 'Combat Knife', image: 'images/weapons/knife.combat' },
        { id: 'bow.compound', name: 'Compound Bow', image: 'images/weapons/bow.compound' },
        { id: 'crossbow', name: 'Crossbow', image: 'images/weapons/crossbow' },
        { id: 'smg.2', name: 'Custom SMG', image: 'images/weapons/smg.2' },
        { id: 'shotgun.double', name: 'Double Barrel Shotgun', image: 'images/weapons/shotgun.double' },
        { id: 'shotgun.m4', name: 'M4 Shotgun', image: 'images/weapons/shotgun.m4' },
        { id: 'pistol.eoka', name: 'Eoka Pistol', image: 'images/weapons/pistol.eoka' },
        { id: 'grenade.f1', name: 'F1 Grenade', image: 'images/weapons/grenade.f1' },
        { id: 'flamethrower', name: 'Flame Thrower', image: 'images/weapons/flamethrower' },
        { id: 'grenade.flashbang', name: 'Flashbang', image: 'images/weapons/grenade.flashbang' },
        { id: 'hmlmg', name: 'HMLMG', image: 'images/weapons/hmlmg' },
        { id: 'bow.hunting', name: 'Hunting Bow', image: 'images/weapons/bow.hunting' },
        { id: 'rifle.l96', name: 'L96 Rifle', image: 'images/weapons/rifle.l96' },
        { id: 'longsword', name: 'Longsword', image: 'images/weapons/longsword' },
        { id: 'rifle.lr300', name: 'LR-300 Assault Rifle', image: 'images/weapons/rifle.lr300' },
        { id: 'lmg.m249', name: 'M249', image: 'images/weapons/lmg.m249' },
        { id: 'rifle.m39', name: 'M39 Rifle', image: 'images/weapons/rifle.m39' },
        { id: 'pistol.m92', name: 'M92 Pistol', image: 'images/weapons/pistol.m92' },
        { id: 'mace', name: 'Mace', image: 'images/weapons/mace' },
        { id: 'machete', name: 'Machete', image: 'images/weapons/machete' },
        { id: 'grenade.molotov', name: 'Molotov Cocktail', image: 'images/weapons/grenade.molotov' },
        { id: 'smg.mp5', name: 'MP5A4', image: 'images/weapons/smg.mp5' },
        { id: 'multiplegrenadelauncher', name: 'Multiple Grenade Launcher', image: 'images/weapons/multiplegrenadelauncher' },
        { id: 'pistol.nailgun', name: 'Nailgun', image: 'images/weapons/pistol.nailgun' },
        { id: 'paddle', name: 'Paddle', image: 'images/weapons/paddle' },
        { id: 'pistol.prototype17', name: 'Prototype 17', image: 'images/weapons/pistol.prototype17' },
        { id: 'shotgun.pump', name: 'Pump Shotgun', image: 'images/weapons/shotgun.pump' },
        { id: 'pistol.python', name: 'Python Revolver', image: 'images/weapons/pistol.python' },
        { id: 'pistol.revolver', name: 'Revolver', image: 'images/weapons/pistol.revolver' },
        { id: 'rocket.launcher', name: 'Rocket Launcher', image: 'images/weapons/rocket.launcher' },
        { id: 'salvaged.cleaver', name: 'Salvaged Cleaver', image: 'images/weapons/salvaged.cleaver' },
        { id: 'salvaged.sword', name: 'Salvaged Sword', image: 'images/weapons/salvaged.sword' },
        { id: 'pistol.semiauto', name: 'Semi-Automatic Pistol', image: 'images/weapons/pistol.semiauto' },
        { id: 'rifle.semiauto', name: 'Semi-Automatic Rifle', image: 'images/weapons/rifle.semiauto' },
        { id: 'shotgun.spas12', name: 'Spas-12 Shotgun', image: 'images/weapons/shotgun.spas12' },
        { id: 'speargun', name: 'Speargun', image: 'images/weapons/speargun' },
        { id: 'spear.stone', name: 'Stone Spear', image: 'images/weapons/spear.stone' },
        { id: 'smg.thompson', name: 'Thompson', image: 'images/weapons/smg.thompson' },
        { id: 'shotgun.waterpipe', name: 'Waterpipe Shotgun', image: 'images/weapons/shotgun.waterpipe' },
        { id: 'spear.wooden', name: 'Wooden Spear', image: 'images/weapons/spear.wooden' }
    ],
    RESOURCES : [
    { id: 'fat.animal', name: 'Animal Fat', image: 'images/resources/fat.animal' },
    { id: 'bone.fragments', name: 'Bone Fragments', image: 'images/resources/bone.fragments' },
    { id: 'cctv.camera', name: 'CCTV Camera', image: 'images/resources/cctv.camera' },
    { id: 'charcoal', name: 'Charcoal', image: 'images/resources/charcoal' },
    { id: 'cloth', name: 'Cloth', image: 'images/resources/cloth' },
    { id: 'crude.oil', name: 'Crude Oil', image: 'images/resources/crude.oil' },
    { id: 'diesel_fuel', name: 'Diesel Fuel', image: 'images/resources/diesel_barrel' },
    { id: 'can.beans.empty', name: 'Empty Can Of Beans', image: 'images/resources/can.beans.empty' },
    { id: 'can.tuna.empty', name: 'Empty Tuna Can', image: 'images/resources/can.tuna.empty' },
    { id: 'explosives', name: 'Explosives', image: 'images/resources/explosives' },
    { id: 'fertilizer', name: 'Fertilizer', image: 'images/resources/fertilizer' },
    { id: 'gunpowder', name: 'Gun Powder', image: 'images/resources/gunpowder' },
    { id: 'metal.refined', name: 'High Quality Metal', image: 'images/resources/high_quality_metal' },
    { id: 'hq.metal.ore', name: 'High Quality Metal Ore', image: 'images/resources/high_quality_metal_ore' },
    { id: 'horsedung', name: 'Horse Dung', image: 'images/resources/horse_dung' },
    { id: 'skull.human', name: 'Human Skull', image: 'images/resources/human_skull' },
    { id: 'leather', name: 'Leather', image: 'images/resources/leather' },
    { id: 'lowgradefuel', name: 'Low Grade Fuel', image: 'images/resources/low_grade_fuel' },
    { id: 'metal.fragments', name: 'Metal Fragments', image: 'images/resources/metal_fragments' },
    { id: 'metal.ore', name: 'Metal Ore', image: 'images/resources/metal_ore' },
    { id: 'plantfiber', name: 'Plant Fiber', image: 'images/resources/plant_fiber' },
    { id: 'water.salt', name: 'Salt Water', image: 'images/resources/salt_water' },
    { id: 'scrap', name: 'Scrap', image: 'images/resources/scrap' },
    { id: 'stones', name: 'Stones', image: 'images/resources/stones' },
    { id: 'sulfur.ore', name: 'Sulfur Ore', image: 'images/resources/sulfur_ore' },
    { id: 'sulfur', name: 'Sulfur', image: 'images/resources/sulfur' },
    { id: 'targeting.computer', name: 'Targeting Computer', image: 'images/resources/targeting_computer' },
    { id: 'water', name: 'Water', image: 'images/resources/water' },
    { id: 'skull.wolf', name: 'Wolf Skull', image: 'images/resources/wolf_skull' },
    { id: 'wood', name: 'Wood', image: 'images/resources/wood' }
],

    CONSTRUCTION: [
        { id: 'door.hinged.toptier', name: 'Armored Door', image: 'images/construction/door.hinged.toptier' },
        { id: 'door.double.hinged.toptier', name: 'Armored Double Door', image: 'images/construction/door.double.hinged.toptier' },
        { id: 'barricade.woodwire', name: 'Barbed Wooden Barricade', image: 'images/construction/barricade.woodwire' },
        { id: 'building.planner', name: 'Building Plan', image: 'images/construction/building.planner' },
        { id: 'wall.frame.fence', name: 'Chainlink Fence', image: 'images/construction/wall.frame.fence' },
        { id: 'wall.frame.fence.gate', name: 'Chainlink Fence Gate', image: 'images/construction/wall.frame.fence.gate' },
        { id: 'lock.code', name: 'Code Lock', image: 'images/construction/lock.code' },
        { id: 'barricade.concrete', name: 'Concrete Barricade', image: 'images/construction/barricade.concrete' },
        { id: 'floor.grill', name: 'Floor Grill', image: 'images/construction/floor.grill' },
        { id: 'floor.triangle.grill', name: 'Floor Triangle Grill', image: 'images/construction/floor.triangle.grill' },
        { id: 'wall.frame.garagedoor', name: 'Garage Door', image: 'images/construction/wall.frame.garagedoor' },
        { id: 'gates.external.high.stone', name: 'High External Stone Gate', image: 'images/construction/gates.external.high.stone' },
        { id: 'gates.external.high.wood', name: 'High External Wooden Gate', image: 'images/construction/gates.external.high.wood' },
        { id: 'wall.external.high.stone', name: 'High External Stone Wall', image: 'images/construction/wall.external.high.stone' },
        { id: 'wall.external.high', name: 'High External Wooden Wall', image: 'images/construction/wall.external.high' },
        { id: 'lock.key', name: 'Key Lock', image: 'images/construction/lock.key' },
        { id: 'floor.ladder.hatch', name: 'Ladder Hatch', image: 'images/construction/floor.ladder.hatch' },
        { id: 'water.catcher.large', name: 'Large Water Catcher', image: 'images/construction/water.catcher.large' },
        { id: 'barricade.metal', name: 'Metal Barricade', image: 'images/construction/barricade.metal' },
        { id: 'shutter.metal.embrasure.a', name: 'Metal Horizontal Embrasure', image: 'images/construction/shutter.metal.embrasure.a' },
        { id: 'wall.frame.shopfront.metal', name: 'Metal Shop Front', image: 'images/construction/wall.frame.shopfront.metal' },
        { id: 'shutter.metal.embrasure.b', name: 'Metal Vertical Embrasure', image: 'images/construction/shutter.metal.embrasure.b' },
        { id: 'wall.window.bars.metal', name: 'Metal Window Bars', image: 'images/construction/wall.window.bars.metal' },
        { id: 'wall.frame.netting', name: 'Netting', image: 'images/construction/wall.frame.netting' },
        { id: 'wall.frame.cell.gate', name: 'Prison Cell Gate', image: 'images/construction/wall.frame.cell.gate' },
        { id: 'wall.frame.cell', name: 'Prison Cell Wall', image: 'images/construction/wall.frame.cell' },
        { id: 'wall.window.bars.toptier', name: 'Reinforced Glass Window', image: 'images/construction/wall.window.bars.toptier' },
        { id: 'barricade.sandbags', name: 'Sandbag Barricade', image: 'images/construction/barricade.sandbags' },
        { id: 'door.hinged.metal', name: 'Sheet Metal Door', image: 'images/construction/door.hinged.metal' },
        { id: 'door.double.hinged.metal', name: 'Sheet Metal Double Door', image: 'images/construction/door.double.hinged.metal' },
        { id: 'wall.frame.shopfront', name: 'Shop Front', image: 'images/construction/wall.frame.shopfront' },
        { id: 'water.catcher.small', name: 'Small Water Catcher', image: 'images/construction/water.catcher.small' },
        { id: 'barricade.stone', name: 'Stone Barricade', image: 'images/construction/barricade.stone' },
        { id: 'wall.window.glass.reinforced', name: 'Strengthened Glass Window', image: 'images/construction/wall.window.glass.reinforced' },
        { id: 'cupboard.tool', name: 'Tool Cupboard', image: 'images/construction/cupboard.tool' },
        { id: 'floor.triangle.ladder.hatch', name: 'Triangle Ladder Hatch', image: 'images/construction/floor.triangle.ladder.hatch' },
        { id: 'watchtower.wood', name: 'Watch Tower', image: 'images/construction/watchtower.wood' },
        { id: 'door.double.hinged.wood', name: 'Wood Double Door', image: 'images/construction/door.double.hinged.wood' },
        { id: 'shutter.wood.a', name: 'Wood Shutters', image: 'images/construction/shutter.wood.a' },
        { id: 'barricade.wood', name: 'Wooden Barricade', image: 'images/construction/barricade.wood' },
        { id: 'barricade.wood.cover', name: 'Wooden Barricade Cover', image: 'images/construction/barricade.wood.cover' },
        { id: 'door.hinged.wood', name: 'Wooden Door', image: 'images/construction/door.hinged.wood' },
        { id: 'box.wooden.large', name: 'Box Large', image: 'images/construction/box.wooden.large' },
        { id: 'furnace', name: 'Furnace', image: 'images/construction/furnace' },
        { id: 'furnace.large', name: 'Large Furnace', image: 'images/construction/furnace.large' },
        { id: 'ladder.wooden.wall', name: 'Wooden Ladder', image: 'images/construction/ladder.wooden.wall' },
        { id: 'wall.window.bars.wood', name: 'Wooden Window Bars', image: 'images/construction/wall.window.bars.wood' },
	{ id: 'planter.large', name: 'Large Planter', image: 'images/construction/planter.large' },
        { id: 'planter.small', name: 'Small Planter', image: 'images/construction/planter.small' },
        { id: 'workbench1', name: 'Workbench 1', image: 'images/construction/workbench1' },
        { id: 'workbench2', name: 'Workbench 2', image: 'images/construction/workbench2' },
        { id: 'workbench3', name: 'Workbench 3', image: 'images/construction/workbench3' },
        { id: 'bed', name: 'Bed', image: 'images/construction/bed' }
 ],

    ATTIRE: [
        { id: 'mask.bandana', name: 'Bandana Mask', image: 'images/attire/mask.bandana' },
        { id: 'barrelcostume', name: 'Barrel Costume', image: 'images/attire/barrelcostume' },
        { id: 'hat.cap', name: 'Baseball Cap', image: 'images/attire/hat.cap' },
        { id: 'hat.beenie', name: 'Beanie Hat', image: 'images/attire/hat.beenie' },
        { id: 'bone.armor.suit', name: 'Bone Armor', image: 'images/attire/bone.armor.suit' },
        { id: 'deer.skull.mask', name: 'Bone Helmet', image: 'images/attire/deer.skull.mask' },
        { id: 'hat.boonie', name: 'Boonie Hat', image: 'images/attire/hat.boonie' },
        { id: 'shoes.boots', name: 'Boots', image: 'images/attire/shoes.boots' },
        { id: 'bucket.helmet', name: 'Bucket Helmet', image: 'images/attire/bucket.helmet' },
        { id: 'burlap.gloves.new', name: 'Burlap Gloves', image: 'images/attire/burlap.gloves.new' },
        { id: 'burlap.headwrap', name: 'Burlap Headwrap', image: 'images/attire/burlap.headwrap' },
        { id: 'burlap.shirt', name: 'Burlap Shirt', image: 'images/attire/burlap.shirt' },
        { id: 'burlap.shoes', name: 'Burlap Shoes', image: 'images/attire/burlap.shoes' },
        { id: 'burlap.trousers', name: 'Burlap Trousers', image: 'images/attire/burlap.trousers' },
        { id: 'hat.candle', name: 'Candle Hat', image: 'images/attire/hat.candle' },
        { id: 'coffeecan.helmet', name: 'Coffee Can Helmet', image: 'images/attire/coffeecan.helmet' },
        { id: 'cratecostume', name: 'Crate Costume', image: 'images/attire/cratecostume' },
        { id: 'diving.fins', name: 'Diving Fins', image: 'images/attire/diving.fins' },
        { id: 'diving.mask', name: 'Diving Mask', image: 'images/attire/diving.mask' },
        { id: 'diving.tank', name: 'Diving Tank', image: 'images/attire/diving.tank' },
        { id: 'boots.frog', name: 'Frog Boots', image: 'images/attire/boots.frog' },
        { id: 'hazmatsuit', name: 'Hazmat Suit', image: 'images/attire/hazmatsuit' },
        { id: 'hazmatsuit_scientist_peacekeeper', name: 'Peacekeeper Hazmat Suit', image: 'images/attire/hazmatsuit_scientist_peacekeeper' },
        { id: 'scientistsuit_heavy', name: 'Heavy Scientist Suit', image: 'images/attire/scientistsuit_heavy' },
        { id: 'heavy.plate.helmet', name: 'Heavy Plate Helmet', image: 'images/attire/heavy.plate.helmet' },
        { id: 'heavy.plate.jacket', name: 'Heavy Plate Jacket', image: 'images/attire/heavy.plate.jacket' },
        { id: 'heavy.plate.pants', name: 'Heavy Plate Pants', image: 'images/attire/heavy.plate.pants' },
        { id: 'attire.hide.boots', name: 'Hide Boots', image: 'images/attire/attire.hide.boots' },
        { id: 'attire.hide.helterneck', name: 'Hide Halterneck', image: 'images/attire/attire.hide.helterneck' },
        { id: 'attire.hide.pants', name: 'Hide Pants', image: 'images/attire/attire.hide.pants' },
        { id: 'attire.hide.poncho', name: 'Hide Poncho', image: 'images/attire/attire.hide.poncho' },
        { id: 'attire.hide.skirt', name: 'Hide Skirt', image: 'images/attire/attire.hide.skirt' },
        { id: 'attire.hide.vest', name: 'Hide Vest', image: 'images/attire/attire.hide.vest' },
        { id: 'hoodie', name: 'Hoodie', image: 'images/attire/hoodie' },
        { id: 'mask.balaclava', name: 'Improvised Balaclava', image: 'images/attire/mask.balaclava' },
        { id: 'jacket', name: 'Jacket', image: 'images/attire/jacket' },
        { id: 'largebackpack', name: 'Large Backpack', image: 'images/attire/largebackpack' },
        { id: 'burlap.gloves', name: 'Leather Gloves', image: 'images/attire/burlap.gloves' },
        { id: 'tshirt.long', name: 'Longsleeve T-Shirt', image: 'images/attire/tshirt.long' },
        { id: 'lumberjack hoodie', name: 'Lumberjack Hoodie', image: 'images/attire/lumberjack hoodie' },
        { id: 'metal.plate.torso', name: 'Metal Chest Plate', image: 'images/attire/metal.plate.torso' },
        { id: 'metal.facemask', name: 'Metal Facemask', image: 'images/attire/metal.facemask' },
        { id: 'hat.miner', name: 'Miners Hat', image: 'images/attire/hat.miner' },
        { id: 'nightvisiongoggles', name: 'Night Vision Goggles', image: 'images/attire/nightvisiongoggles' },
        { id: 'pants', name: 'Pants', image: 'images/attire/pants' },
        { id: 'partyhat', name: 'Party Hat', image: 'images/attire/partyhat' },
        { id: 'riot.helmet', name: 'Riot Helmet', image: 'images/attire/riot.helmet' },
        { id: 'roadsign.gloves', name: 'Roadsign Gloves', image: 'images/attire/roadsign.gloves' },
        { id: 'roadsign.jacket', name: 'Road Sign Jacket', image: 'images/attire/roadsign.jacket' },
        { id: 'roadsign.kilt', name: 'Road Sign Kilt', image: 'images/attire/roadsign.kilt' },
        { id: 'shirt.collared', name: 'Shirt', image: 'images/attire/shirt.collared' },
        { id: 'pants.shorts', name: 'Shorts', image: 'images/attire/pants.shorts' },
        { id: 'smallbackpack', name: 'Small Backpack', image: 'images/attire/smallbackpack' },
        { id: 'jacket.snow', name: 'Snow Jacket', image: 'images/attire/jacket.snow' },
        { id: 'tactical.gloves', name: 'Tactical Gloves', image: 'images/attire/tactical.gloves' },
        { id: 'shirt.tanktop', name: 'Tank Top', image: 'images/attire/shirt.tanktop' },
        { id: 'tshirt', name: 'T-Shirt', image: 'images/attire/tshirt' },
        { id: 'diving.wetsuit', name: 'Wetsuit', image: 'images/attire/diving.wetsuit' },
        { id: 'hat.wolf', name: 'Wolf Headdress', image: 'images/attire/hat.wolf' },
        { id: 'wood.armor.helmet', name: 'Wood Armor Helmet', image: 'images/attire/wood.armor.helmet' },
        { id: 'wood.armor.pants', name: 'Wood Armor Pants', image: 'images/attire/wood.armor.pants' },
        { id: 'wood.armor.jacket', name: 'Wood Chestplate', image: 'images/attire/wood.armor.jacket' }
    ],
    TOOLS: [
        { id: 'tool.binoculars', name: 'Binoculars', image: 'images/tools/tool.binoculars' },
        { id: 'wiretool', name: 'Wire', image: 'images/tools/wiretool' },
        { id: 'cakefiveyear', name: 'Birthday Cake', image: 'images/tools/cakefiveyear' },
        { id: 'chainsaw', name: 'Chainsaw', image: 'images/tools/chainsaw' },
        { id: 'flare', name: 'Flare', image: 'images/tools/flare' },
        { id: 'flashlight.held', name: 'Flashlight', image: 'images/tools/flashlight.held' },
        { id: 'hammer', name: 'Hammer', image: 'images/tools/hammer' },
        { id: 'fishingrod.handmade', name: 'Handmade Fishing Rod', image: 'images/tools/fishingrod.handmade' },
        { id: 'hatchet', name: 'Hatchet', image: 'images/tools/hatchet' },
        { id: 'jackhammer', name: 'Jackhammer', image: 'images/tools/jackhammer' },
        { id: 'pickaxe', name: 'Pickaxe', image: 'images/tools/pickaxe' },
        { id: 'pipetool', name: 'Pipe Tool', image: 'images/tools/pipetool' },
        { id: 'rf.detonator', name: 'RF Transmitter', image: 'images/tools/rf.detonator' },
        { id: 'rock', name: 'Rock', image: 'images/tools/rock' },
        { id: 'axe.salvaged', name: 'Salvaged Axe', image: 'images/tools/axe.salvaged' },
        { id: 'hammer.salvaged', name: 'Salvaged Hammer', image: 'images/tools/hammer.salvaged' },
        { id: 'icepick.salvaged', name: 'Salvaged Icepick', image: 'images/tools/icepick.salvaged' },
        { id: 'explosive.satchel', name: 'Satchel Charge', image: 'images/tools/explosive.satchel' },
        { id: 'grenade.smoke', name: 'Smoke Grenade', image: 'images/tools/grenade.smoke' },
        { id: 'spraycan', name: 'Spray Can', image: 'images/tools/spraycan' },
        { id: 'stonehatchet', name: 'Stone Hatchet', image: 'images/tools/stonehatchet' },
        { id: 'stone.pickaxe', name: 'Stone Pickaxe', image: 'images/tools/stone.pickaxe' },
        { id: 'supply.signal', name: 'Supply Signal', image: 'images/tools/supply.signal' },
        { id: 'torch', name: 'Torch', image: 'images/tools/torch' },
        { id: 'bucket.water', name: 'Water Bucket', image: 'images/tools/bucket.water' }
    ],
    MEDSANDTEAS: [
        { id: 'antiradpills', name: 'Anti-Radiation Pills', image: 'images/medsAndTeas/antiradpills' },
        { id: 'blueberries', name: 'Blueberries', image: 'images/medsAndTeas/blueberries' },
        { id: 'pumpkin', name: 'Pumpkin', image: 'images/medsAndTeas/pumpkin' },
        { id: 'bandage', name: 'Bandage', image: 'images/medsAndTeas/bandage' },
        { id: 'largemedkit', name: 'Large Medkit', image: 'images/medsAndTeas/largemedkit' },
        { id: 'syringe.medical', name: 'Medical Syringe', image: 'images/medsAndTeas/syringe.medical' },
        { id: 'radiationresisttea.advanced', name: 'Advanced Anti-Rad Tea', image: 'images/medsAndTeas/radiationresisttea.advanced' },
        { id: 'healingtea.advanced', name: 'Advanced Healing Tea', image: 'images/medsAndTeas/healingtea.advanced' },
        { id: 'maxhealthtea.advanced', name: 'Advanced Max Health Tea', image: 'images/medsAndTeas/maxhealthtea.advanced' },
        { id: 'oretea.advanced', name: 'Advanced Ore Tea', image: 'images/medsAndTeas/oretea.advanced' },
        { id: 'radiationremovetea.advanced', name: 'Advanced Rad. Removal Tea', image: 'images/medsAndTeas/radiationremovetea.advanced' },
        { id: 'scraptea.advanced', name: 'Advanced Scrap Tea', image: 'images/medsAndTeas/scraptea.advanced' },
        { id: 'woodtea.advanced', name: 'Advanced Wood Tea', image: 'images/medsAndTeas/woodtea.advanced' },
        { id: 'radiationresisttea', name: 'Anti-Rad Tea', image: 'images/medsAndTeas/radiationresisttea' },
        { id: 'healingtea', name: 'Basic Healing Tea', image: 'images/medsAndTeas/healingtea' },
        { id: 'maxhealthtea', name: 'Basic Max Health Tea', image: 'images/medsAndTeas/maxhealthtea' },
        { id: 'oretea', name: 'Basic Ore Tea', image: 'images/medsAndTeas/oretea' },
        { id: 'scraptea', name: 'Basic Scrap Tea', image: 'images/medsAndTeas/scraptea' },
        { id: 'woodtea', name: 'Basic Wood Tea', image: 'images/medsAndTeas/woodtea' },
        { id: 'radiationresisttea.pure', name: 'Pure Anti-Rad Tea', image: 'images/medsAndTeas/radiationresisttea.pure' },
        { id: 'healingtea.pure', name: 'Pure Healing Tea', image: 'images/medsAndTeas/healingtea.pure' },
        { id: 'maxhealthtea.pure', name: 'Pure Max Health Tea', image: 'images/medsAndTeas/maxhealthtea.pure' },
        { id: 'oretea.pure', name: 'Pure Ore Tea', image: 'images/medsAndTeas/oretea.pure' },
        { id: 'radiationremovetea.pure', name: 'Pure Rad. Removal Tea', image: 'images/medsAndTeas/radiationremovetea.pure' },
        { id: 'scraptea.pure', name: 'Pure Scrap Tea', image: 'images/medsAndTeas/scraptea.pure' },
        { id: 'woodtea.pure', name: 'Pure Wood Tea', image: 'images/medsAndTeas/woodtea.pure' },
        { id: 'radiationremovetea', name: 'Rad. Removal Tea', image: 'images/medsAndTeas/radiationremovetea' }
    ],
FOOD: [
    { id: 'fish.raw', name: 'Raw Fish', image: 'images/food/fish.raw' },
    { id: 'fish.anchovy', name: 'Anchovy', image: 'images/food/fish.anchovy' },
    { id: 'fish.catfish', name: 'Catfish', image: 'images/food/fish.catfish' },
    { id: 'fish.herring', name: 'Herring', image: 'images/food/fish.herring' },
    { id: 'fish.minnows', name: 'Minnows', image: 'images/food/fish.minnows' },
    { id: 'fish.orangeroughy', name: 'Orange Roughy', image: 'images/food/fish.orangeroughy' },
    { id: 'fish.salmon', name: 'Salmon', image: 'images/food/fish.salmon' },
    { id: 'fish.sardine', name: 'Sardine', image: 'images/food/fish.sardine' },
    { id: 'fish.smallshark', name: 'Small Shark', image: 'images/food/fish.smallshark' },
    { id: 'fish.troutsmall', name: 'Small Trout', image: 'images/food/fish.troutsmall' },
    { id: 'fish.cooked', name: 'Cooked Fish', image: 'images/food/fish.cooked' },
    { id: 'bearmeat', name: 'Raw Bear Meat', image: 'images/food/bearmeat' },
    { id: 'chicken.raw', name: 'Raw Chicken Breast', image: 'images/food/chicken.raw' },
    { id: 'deermeat.raw', name: 'Raw Deer Meat', image: 'images/food/deermeat.raw' },
    { id: 'horsemeat.raw', name: 'Raw Horse Meat', image: 'images/food/horsemeat.raw' },
    { id: 'humanmeat.raw', name: 'Raw Human Meat', image: 'images/food/humanmeat.raw' },
    { id: 'meat.boar', name: 'Raw Pork', image: 'images/food/meat.boar' },
    { id: 'wolfmeat.raw', name: 'Raw Wolf Meat', image: 'images/food/wolfmeat.raw' },
    { id: 'bearmeat.cooked', name: 'Cooked Bear Meat', image: 'images/food/bearmeat.cooked' },
    { id: 'chicken.cooked', name: 'Cooked Chicken', image: 'images/food/chicken.cooked' },
    { id: 'deermeat.cooked', name: 'Cooked Deer Meat', image: 'images/food/deermeat.cooked' },
    { id: 'horsemeat.cooked', name: 'Cooked Horse Meat', image: 'images/food/horsemeat.cooked' },
    { id: 'humanmeat.cooked', name: 'Cooked Human Meat', image: 'images/food/humanmeat.cooked' },
    { id: 'meat.pork.cooked', name: 'Cooked Pork', image: 'images/food/meat.pork.cooked' },
    { id: 'wolfmeat.cooked', name: 'Cooked Wolf Meat', image: 'images/food/wolfmeat.cooked' },
    { id: 'bearmeat.burned', name: 'Burnt Bear Meat', image: 'images/food/bearmeat.burned' },
    { id: 'chicken.burned', name: 'Burnt Chicken', image: 'images/food/chicken.burned' },
    { id: 'deermeat.burned', name: 'Burnt Deer Meat', image: 'images/food/deermeat.burned' },
    { id: 'horsemeat.burned', name: 'Burnt Horse Meat', image: 'images/food/horsemeat.burned' },
    { id: 'humanmeat.burned', name: 'Burnt Human Meat', image: 'images/food/humanmeat.burned' },
    { id: 'meat.pork.burned', name: 'Burnt Pork', image: 'images/food/meat.pork.burned' },
    { id: 'wolfmeat.burned', name: 'Burnt Wolf Meat', image: 'images/food/wolfmeat.burned' },
    { id: 'apple', name: 'Apple', image: 'images/food/apple' },
    { id: 'black.raspberries', name: 'Black Raspberries', image: 'images/food/black.raspberries' },
    { id: 'blue.berry', name: 'Blue Berry', image: 'images/food/blue.berry' },
    { id: 'blueberries', name: 'Blueberries', image: 'images/food/blueberries' },
    { id: 'corn', name: 'Corn', image: 'images/food/corn' },
    { id: 'green.berry', name: 'Green Berry', image: 'images/food/green.berry' },
    { id: 'mushroom', name: 'Mushroom', image: 'images/food/mushroom' },
    { id: 'potato', name: 'Potato', image: 'images/food/potato' },
    { id: 'pumpkin', name: 'Pumpkin', image: 'images/food/pumpkin' },
    { id: 'red.berry', name: 'Red Berry', image: 'images/food/red.berry' },
    { id: 'white.berry', name: 'White Berry', image: 'images/food/white.berry' },
    { id: 'yellow.berry', name: 'Yellow Berry', image: 'images/food/yellow.berry' },
    { id: 'can.beans', name: 'Can of Beans', image: 'images/food/can.beans' },
    { id: 'can.tuna', name: 'Can of Tuna', image: 'images/food/can.tuna' },
    { id: 'cactusflesh', name: 'Cactus Flesh', image: 'images/food/cactusflesh' },
    { id: 'granolabar', name: 'Granola Bar', image: 'images/food/granolabar' },
    { id: 'grub', name: 'Grub', image: 'images/food/grub' },
    { id: 'jar.pickle', name: 'Pickles', image: 'images/food/jar.pickle' },
    { id: 'chocholate', name: 'Chocolate Bar', image: 'images/food/chocolate' },
    { id: 'clone.blue.berry', name: 'Blue Berry Clone', image: 'images/food/clone.blue.berry' },
    { id: 'clone.corn', name: 'Corn Clone', image: 'images/food/clone.corn' },
    { id: 'clone.green.berry', name: 'Green Berry Clone', image: 'images/food/clone.green.berry' },
    { id: 'clone.hemp', name: 'Hemp Clone', image: 'images/food/clone.hemp' },
    { id: 'clone.potato', name: 'Potato Clone', image: 'images/food/clone.potato' },
    { id: 'clone.pumpkin', name: 'Pumpkin Plant Clone', image: 'images/food/clone.pumpkin' },
    { id: 'clone.red.berry', name: 'Red Berry Clone', image: 'images/food/clone.red.berry' },
    { id: 'clone.white.berry', name: 'White Berry Clone', image: 'images/food/clone.white.berry' },
    { id: 'clone.yellow.berry', name: 'Yellow Berry Clone', image: 'images/food/clone.yellow.berry' },
    { id: 'seed.blue.berry', name: 'Blue Berry Seed', image: 'images/food/seed.blue.berry' },
    { id: 'seed.corn', name: 'Corn Seed', image: 'images/food/seed.corn' },
    { id: 'seed.green.berry', name: 'Green Berry Seed', image: 'images/food/seed.green.berry' },
    { id: 'seed.hemp', name: 'Hemp Seed', image: 'images/food/seed.hemp' },
    { id: 'seed.potato', name: 'Potato Seed', image: 'images/food/seed.potato' },
    { id: 'seed.pumpkin', name: 'Pumpkin Seed', image: 'images/food/seed.pumpkin' },
    { id: 'seed.red.berry', name: 'Red Berry Seed', image: 'images/food/seed.red.berry' },
    { id: 'seed.white.berry', name: 'White Berry Seed', image: 'images/food/seed.white.berry' },
    { id: 'seed.yellow.berry', name: 'Yellow Berry Seed', image: 'images/food/seed.yellow.berry' }
],

    TRAPSANDMISCELLANEOUS: [
        { id: 'flameturret', name: 'Flame Turret', image: 'images/trapsAndMiscellaneous/flameturret' },
        { id: 'trap.landmine', name: 'Landmine', image: 'images/trapsAndMiscellaneous/trap.landmine' },
        { id: 'guntrap', name: 'Shotgun Trap', image: 'images/trapsAndMiscellaneous/guntrap' },
        { id: 'trap.bear', name: 'Snap Trap', image: 'images/trapsAndMiscellaneous/trap.bear' },
        { id: 'spikes.floor', name: 'Wooden Floor Spikes', image: 'images/trapsAndMiscellaneous/spikes.floor' },    
        { id: 'keycard_blue', name: 'Blue Keycard', image: 'images/trapsAndMiscellaneous/keycard_blue' },
        { id: 'door.key', name: 'Door Key', image: 'images/trapsAndMiscellaneous/door.key' },
        { id: 'keycard_green', name: 'Green Keycard', image: 'images/trapsAndMiscellaneous/keycard_green' },
        { id: 'fun.guitar', name: 'Guitar', image: 'images/trapsAndMiscellaneous/fun.guitar' },
        { id: 'note', name: 'Note', image: 'images/trapsAndMiscellaneous/note' },
        { id: 'keycard_red', name: 'Red Keycard', image: 'images/trapsAndMiscellaneous/keycard_red' }
    ],
    COMPONENTS: [
        { id: 'fuse', name: 'Electric Fuse', image: 'images/components/fuse' },
        { id: 'propanetank', name: 'Empty Propane Tank', image: 'images/components/propanetank' },
        { id: 'gears', name: 'Gears', image: 'images/components/gears' },
        { id: 'metalblade', name: 'Metal Blade', image: 'images/components/metalblade' },
        { id: 'metalpipe', name: 'Metal Pipe', image: 'images/components/metalpipe' },
        { id: 'metalspring', name: 'Metal Spring', image: 'images/components/metalspring' },
        { id: 'riflebody', name: 'Rifle Body', image: 'images/components/riflebody' },
        { id: 'roadsigns', name: 'Road Signs', image: 'images/components/roadsigns' },
        { id: 'rope', name: 'Rope', image: 'images/components/rope' },
        { id: 'semibody', name: 'Semi Automatic Body', image: 'images/components/semibody' },
        { id: 'sewingkit', name: 'Sewing Kit', image: 'images/components/sewingkit' },
        { id: 'sheetmetal', name: 'Sheet Metal', image: 'images/components/sheetmetal' },
        { id: 'smgbody', name: 'SMG Body', image: 'images/components/smgbody' },
        { id: 'tarp', name: 'Tarp', image: 'images/components/tarp' },
        { id: 'techparts', name: 'Tech Trash', image: 'images/components/techparts' }
    ],
    ELECTRICAL: [
        { id: 'electric.andswitch', name: 'AND Switch', image: 'images/electrical/electric.andswitch' },
        { id: 'electric.audioalarm', name: 'Audio Alarm', image: 'images/electrical/electric.audioalarm' },
        { id: 'autoturret', name: 'Auto Turret', image: 'images/electrical/autoturret' },
        { id: 'electric.blocker', name: 'Blocker', image: 'images/electrical/electric.blocker' },
        { id: 'electric.button', name: 'Button', image: 'images/electrical/electric.button' },
        { id: 'ceilinglight', name: 'Ceiling Light', image: 'images/electrical/ceilinglight' },
        { id: 'computerstation', name: 'Computer Station', image: 'images/electrical/computerstation' },
        { id: 'electric.counter', name: 'Counter', image: 'images/electrical/electric.counter' },
        { id: 'electric.doorcontroller', name: 'Door Controller', image: 'images/electrical/electric.doorcontroller' },
        { id: 'electrical.branch', name: 'Electrical Branch', image: 'images/electrical/electrical.branch' },
        { id: 'electric.furnace', name: 'Electric Furnace', image: 'images/electrical/electric.furnace' },
        { id: 'electric.heater', name: 'Electric Heater', image: 'images/electrical/electric.heater' },
        { id: 'elevator', name: 'Elevator', image: 'images/electrical/elevator' },
        { id: 'electric.flasherlight', name: 'Flasher Light', image: 'images/electrical/electric.flasherlight' },
        { id: 'fluid.combiner', name: 'Fluid Combiner', image: 'images/electrical/fluid.combiner' },
        { id: 'fluid.splitter', name: 'Fluid Splitter', image: 'images/electrical/fluid.splitter' },
        { id: 'fluid.switch', name: 'Fluid Switch & Pump', image: 'images/electrical/fluid.switch' },
        { id: 'electric.hbhfsensor', name: 'HBHF Sensor', image: 'images/electrical/electric.hbhfsensor' },
        { id: 'hosetool', name: 'Hose Tool', image: 'images/electrical/hosetool' },
        { id: 'electric.igniter', name: 'Igniter', image: 'images/electrical/electric.igniter' },
        { id: 'industrial.combiner', name: 'Industrial Combiner', image: 'images/electrical/industrial.combiner' },
        { id: 'industrial.conveyor', name: 'Industrial Conveyor', image: 'images/electrical/industrial.conveyor' },
        { id: 'industrial.crafter', name: 'Industrial Crafter', image: 'images/electrical/industrial.crafter' },
        { id: 'industrial.splitter', name: 'Industrial Splitter', image: 'images/electrical/industrial.splitter' },
        { id: 'electric.battery.rechargable.large', name: 'Large Rechargeable Battery', image: 'images/electrical/electric.battery.rechargable.large' },
        { id: 'electric.solarpanel.large', name: 'Large Solar Panel', image: 'images/electrical/electric.solarpanel.large' },
        { id: 'electric.laserdetector', name: 'Laser Detector', image: 'images/electrical/electric.laserdetector' },
        { id: 'electric.battery.rechargable.medium', name: 'Medium Rechargeable Battery', image: 'images/electrical/electric.battery.rechargable.medium' },
        { id: 'electrical.memorycell', name: 'Memory Cell', image: 'images/electrical/electrical.memorycell' },
        { id: 'electric.orswitch', name: 'OR Switch', image: 'images/electrical/electric.orswitch' },
        { id: 'powered.water.purifier', name: 'Powered Water Purifier', image: 'images/electrical/powered.water.purifier' },
        { id: 'electric.pressurepad', name: 'Pressure Pad', image: 'images/electrical/electric.pressurepad' },
        { id: 'electric.random.switch', name: 'RAND Switch', image: 'images/electrical/electric.random.switch' },
        { id: 'target.reactive', name: 'Reactive Target', image: 'images/electrical/target.reactive' },
        { id: 'electric.rf.broadcaster', name: 'RF Broadcaster', image: 'images/electrical/electric.rf.broadcaster' },
        { id: 'rf_pager', name: 'RF Pager', image: 'images/electrical/rf_pager' },
        { id: 'electric.rf.receiver', name: 'RF Receiver', image: 'images/electrical/electric.rf.receiver' },
        { id: 'electrical.combiner', name: 'Root Combiner', image: 'images/electrical/electrical.combiner' },
        { id: 'searchlight', name: 'Search Light', image: 'images/electrical/searchlight' },
        { id: 'electric.seismicsensor', name: 'Seismic Sensor', image: 'images/electrical/electric.seismicsensor' },
        { id: 'electric.sirenlight', name: 'Siren Light', image: 'images/electrical/electric.sirenlight' },
        { id: 'electric.battery.rechargable.small', name: 'Small Rechargeable Battery', image: 'images/electrical/electric.battery.rechargable.small' },
        { id: 'electric.fuelgenerator.small', name: 'Small Generator', image: 'images/electrical/electric.fuelgenerator.small' },
        { id: 'electric.splitter', name: 'Splitter', image: 'images/electrical/electric.splitter' },
        { id: 'electric.sprinkler', name: 'Sprinkler', image: 'images/electrical/electric.sprinkler' },
        { id: 'storageadapter', name: 'Storage Adapter', image: 'images/electrical/storageadapter' },
        { id: 'storage.monitor', name: 'Storage Monitor', image: 'images/electrical/storage.monitor' },
        { id: 'electric.switch', name: 'Switch', image: 'images/electrical/electric.switch' },
        { id: 'electric.teslacoil', name: 'Tesla Coil', image: 'images/electrical/electric.teslacoil' },
        { id: 'electric.generator.small', name: 'Test Generator', image: 'images/electrical/electric.generator.small' },
        { id: 'electric.timer', name: 'Timer', image: 'images/electrical/electric.timer' },
        { id: 'waterpump', name: 'Water Pump', image: 'images/electrical/waterpump' },
        { id: 'generator.wind.scrap', name: 'Wind Turbine', image: 'images/electrical/generator.wind.scrap' }
    ],
    EASTER: [
        { id: 'easter.bronzeegg', name: 'Bronze Egg', image: 'images/easter/easter.bronzeegg' },
        { id: 'attire.bunnyears', name: 'Bunny Ears', image: 'images/easter/attire.bunnyears' },
        { id: 'attire.bunny.onesie', name: 'Bunny Onesie', image: 'images/easter/attire.bunny.onesie' },
        { id: 'easterbasket', name: 'Egg Basket', image: 'images/easter/easterbasket' },
        { id: 'easter.goldegg', name: 'Gold Egg', image: 'images/easter/easter.goldegg' },
        { id: 'easter.paintedeggs', name: 'Painted Egg', image: 'images/easter/easter.paintedeggs' },
        { id: 'easter.silveregg', name: 'Silver Egg', image: 'images/easter/easter.silveregg' }
    ],
    HALLOWEEN: [
        { id: 'knife.butcher', name: 'Butcher Knife', image: 'images/halloween/knife.butcher' },
        { id: 'coffin.storage', name: 'Coffin', image: 'images/halloween/coffin.storage' },
        { id: 'gravestone', name: 'Gravestone', image: 'images/halloween/gravestone' },
        { id: 'wall.graveyard.fence', name: 'Graveyard Fence', image: 'images/halloween/wall.graveyard.fence' },
        { id: 'halloween.candy', name: 'Halloween Candy', image: 'images/halloween/halloween.candy' },
        { id: 'halloween.lootbag.large', name: 'Large Loot Bag', image: 'images/halloween/halloween.lootbag.large' },
        { id: 'halloween.lootbag.medium', name: 'Medium Loot Bag', image: 'images/halloween/halloween.lootbag.medium' },
        { id: 'halloween.mummysuit', name: 'Mummy Suit', image: 'images/halloween/halloween.mummysuit' },
        { id: 'pitchfork', name: 'Pitchfork', image: 'images/halloween/pitchfork' },
        { id: 'pumpkinbasket', name: 'Pumpkin Bucket', image: 'images/halloween/pumpkinbasket' },
        { id: 'scarecrow', name: 'Scarecrow', image: 'images/halloween/scarecrow' },
        { id: 'scarecrow.suit', name: 'Scarecrow Suit', image: 'images/halloween/scarecrow.suit' },
        { id: 'scarecrowhead', name: 'Scarecrow Wrap', image: 'images/halloween/scarecrowhead' },
        { id: 'sickle', name: 'Sickle', image: 'images/halloween/sickle' },
        { id: 'halloween.lootbag.small', name: 'Small Loot Bag', image: 'images/halloween/halloween.lootbag.small' },
        { id: 'spiderweb', name: 'Spider Webs', image: 'images/halloween/spiderweb' },
        { id: 'woodcross', name: 'Wooden Cross', image: 'images/halloween/woodcross' }
    ],
    XMAS: [
        { id: 'candycane', name: 'Candy Cane', image: 'images/xmas/candycane' },
        { id: 'candycaneclub', name: 'Candy Cane Club', image: 'images/xmas/candycaneclub' },
        { id: 'xmas.lightstring', name: 'Christmas Lights', image: 'images/xmas/xmas.lightstring' },
        { id: 'xmas.tree', name: 'Christmas Tree', image: 'images/xmas/xmas.tree' },
        { id: 'coal', name: 'Coal', image: 'images/xmas/coal' },
        { id: 'xmas.decoration.baubels', name: 'Decorative Baubles', image: 'images/xmas/xmas.decoration.baubels' },
        { id: 'xmas.decoration.gingerbreadmen', name: 'Decorative Gingerbread Men', image: 'images/xmas/xmas.decoration.gingerbreadmen' },
        { id: 'xmas.decoration.pinecone', name: 'Decorative Pinecones', image: 'images/xmas/xmas.decoration.pinecone' },
        { id: 'xmas.decoration.candycanes', name: 'Decorative Plastic Candy Canes', image: 'images/xmas/xmas.decoration.candycanes' },
        { id: 'xmas.decoration.tinsel', name: 'Decorative Tinsel', image: 'images/xmas/xmas.decoration.tinsel' },
        { id: 'gingerbreadsuit', name: 'Gingerbread Suit', image: 'images/xmas/gingerbreadsuit' },
        { id: 'wall.external.high.ice', name: 'High Ice Wall', image: 'images/xmas/wall.external.high.ice' },
        { id: 'xmas.present.large', name: 'Large Present', image: 'images/xmas/xmas.present.large' },
        { id: 'stocking.large', name: 'Large Stocking', image: 'images/xmas/stocking.large' },
        { id: 'xmas.present.medium', name: 'Medium Present', image: 'images/xmas/xmas.present.medium' },
        { id: 'xmas.present.small', name: 'Small Present', image: 'images/xmas/xmas.present.small' },
        { id: 'stocking.small', name: 'Small Stocking', image: 'images/xmas/stocking.small' },
        { id: 'snowball', name: 'Snowball', image: 'images/xmas/snowball' },
        { id: 'snowballgun', name: 'Snowball Gun', image: 'images/xmas/snowballgun' },
        { id: 'xmas.decoration.star', name: 'Star Tree Topper', image: 'images/xmas/xmas.decoration.star' },
        { id: 'xmas.decoration.lights', name: 'Tree Lights', image: 'images/xmas/xmas.decoration.lights' }
    ]
}; // Cerrar correctamente el objeto 'items'

